### ISSUE TITLE
check-against-readme always looks for the project-level README

### ISSUE THREAD

**Issue by markgoho** [bahmutov/check-code-coverage#16]
The token is definitely being passed in, but for whatever reason isn't being found.

``` bash
 Ensure coverage has not dropped 📈4s
    GITHUB_TOKEN: ***
Run DEBUG=check-code-coverage npx set-gh-status --check-against-readme
  DEBUG=check-code-coverage npx set-gh-status --check-against-readme
  shell: /bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
npx: installed 69 in 3.549s
Token must be provided!
##[error]Process completed with exit code 1.
```

It looks like this package assumes everything is at the root folder. After adding `cd clients/html &&` to the npx line, it works, but then it's looking for the badge at the _root-level_ `README` which doesn't have a badge.

**Comment by bahmutov** [comment]
Weird, the code is pretty straightforward here https://github.com/bahmutov/check-code-coverage/blob/master/bin/set-gh-status.js#L101

Is your action written like this?

```
- name: Ensure coverage has not dropped 📈
  run: npx set-gh-status --check-against-readme
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Is this a local pull request or a request from a forked repository?
