### ISSUE TITLE
Examples of how to use set-gh-status inside Github Workflow have error

### ISSUE THREAD

**Issue by leosuncin** [bahmutov/check-code-coverage#28]
There is a package called [set-gh-status](npm.im/set-gh-status) in NPM registry, so using `npx set-gh-startus` will not work as expected, the correct snippet is:

```yaml
- name: Set code coverage commit status 📫
  run: npx -p check-code-coverage set-gh-status
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I will make a pull request to fix these errors.

**Comment by leosuncin** [comment]
Alternative example:

```yaml
- name: Set code coverage commit status 📫
  run: npx --no-install set-gh-status
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
